{
    "correct": 0,
    "error": "[NbClientApp] Executing .laborantum/texts/course/1-Preparation/4-Coding-Backpropagation/task.ipynb\n0.00s - Debugger warning: It seems that frozen modules are being used, which may\n0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off\n0.00s - to python to disable frozen modules.\n0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.\n[NbClientApp] Executing notebook with kernel: container_env\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/jupyter_core/utils/__init__.py\", line 154, in wrapped\n    asyncio.get_running_loop()\nRuntimeError: no running event loop\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/bin/jupyter-execute\", line 8, in <module>\n    sys.exit(main())\n             ^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/jupyter_core/application.py\", line 284, in launch_instance\n    super().launch_instance(argv=argv, **kwargs)\n  File \"/usr/local/lib/python3.11/site-packages/traitlets/config/application.py\", line 1074, in launch_instance\n    app.initialize(argv)\n  File \"/usr/local/lib/python3.11/site-packages/traitlets/config/application.py\", line 118, in inner\n    return method(app, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/nbclient/cli.py\", line 161, in initialize\n    self.run_notebook(path)\n  File \"/usr/local/lib/python3.11/site-packages/nbclient/cli.py\", line 215, in run_notebook\n    client.execute()\n  File \"/usr/local/lib/python3.11/site-packages/jupyter_core/utils/__init__.py\", line 158, in wrapped\n    return loop.run_until_complete(inner)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 654, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/nbclient/client.py\", line 709, in async_execute\n    await self.async_execute_cell(\n  File \"/usr/local/lib/python3.11/site-packages/nbclient/client.py\", line 1062, in async_execute_cell\n    await self._check_raise_for_error(cell, cell_index, exec_reply)\n  File \"/usr/local/lib/python3.11/site-packages/nbclient/client.py\", line 918, in _check_raise_for_error\n    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)\nnbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:\n------------------\n# TEST 8 (Graph)\n\ndef sigmoid(z):\n    return 1 / (1 - np.exp(-z))\n\ndef tanh(z):\n    return np.tanh(z)\n\ndef graph_value(x, w):\n    y = x\n    ## YOUR CODE HERE ##\n    return y\n\nanswer['graph'] = []\nfor inp in inputs1:\n\n    x = inp['x']\n    w = inp['w']\n\n    x = [Node(float(val)) for val in x]\n    w = [Node(float(val)) for val in w]\n\n    y = graph_value(x, w)\n    y.backward()\n\n    answer['graph'].append([x[0].grad, x[1].grad, w[0].grad, w[1].grad, w[2].grad, w[3].grad])\n\nprint(\"OUR RESULTS:\")\nprint(x[0].grad, x[1].grad, w[0].grad, w[1].grad, w[2].grad, w[3].grad)\n\ndef torch_graph_value(x, w):\n    y = x\n\n\n\n    ## YOUR CODE HERE ##\n    return y\n\nimport torch\nx = torch.tensor(inp['x'], requires_grad=True, dtype=float)\nw = torch.tensor(inp['w'], requires_grad=True, dtype=float)\n\ny = torch_graph_value(x, w)\ny.backward()\n\nprint(\"TORCH RESULTS:\")\nprint(x.grad, w.grad)\n    \n------------------\n\n\n\u001b[31m---------------------------------------------------------------------------\u001b[39m\n\u001b[31mAttributeError\u001b[39m                            Traceback (most recent call last)\n\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[12]\u001b[39m\u001b[32m, line 24\u001b[39m\n\u001b[32m     21\u001b[39m     w = [Node(\u001b[38;5;28mfloat\u001b[39m(val)) \u001b[38;5;28;01mfor\u001b[39;00m val \u001b[38;5;129;01min\u001b[39;00m w]\n\u001b[32m     23\u001b[39m     y = graph_value(x, w)\n\u001b[32m---> \u001b[39m\u001b[32m24\u001b[39m     \u001b[43my\u001b[49m\u001b[43m.\u001b[49m\u001b[43mbackward\u001b[49m()\n\u001b[32m     26\u001b[39m     answer[\u001b[33m'\u001b[39m\u001b[33mgraph\u001b[39m\u001b[33m'\u001b[39m].append([x[\u001b[32m0\u001b[39m].grad, x[\u001b[32m1\u001b[39m].grad, w[\u001b[32m0\u001b[39m].grad, w[\u001b[32m1\u001b[39m].grad, w[\u001b[32m2\u001b[39m].grad, w[\u001b[32m3\u001b[39m].grad])\n\u001b[32m     28\u001b[39m \u001b[38;5;28mprint\u001b[39m(\u001b[33m\"\u001b[39m\u001b[33mOUR RESULTS:\u001b[39m\u001b[33m\"\u001b[39m)\n\n\u001b[31mAttributeError\u001b[39m: 'list' object has no attribute 'backward'\n\n"
}